language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run testonce
  - npm run build
after_success:
  - npm run semantic-release
